version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    groups:
      windows:
        patterns: ["windows*"]
      other:
        patterns: ["*"]
        exclude-patterns: ["windows*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
